name: Release

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  release:
    types: [created]

jobs:
  goreleaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Run GoReleaser
        uses: testifysec/witness-run-action@40aa4ef36fc431a37de7c3faebcb66513c03b934
        with:
          step: goreleaser
          pre-command: curl -L https://github.com/ChaosInTheCRD/goreleaser-action/archive/refs/tags/v1.3.0.tar.gz | tar xz --strip=1 -C .
          attestations: "git github environment"
          command: |
            ls
