name: Release

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

on:
  release:
    types: [created]

jobs:
  releasevex:
    env:
      VERSION: "latest"
      ARGS: "release --clean"
      GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          repository: chaosinthecrd/vexctl
          ref: commit-release-feat
          path: ../
      - name: Build vexctl
        run: "go build ../"
      - name: Run vexctl
        run: "../vexctl release"
