name: Send Request

on:
  schedule:
  - cron: "*/2 * * * *"
  workflow_dispatch:
    inputs: {}

jobs:
  sync:
    name: Send API Request
    runs-on: ubuntu-latest
    steps:

    - name: Run
      env:
      run: |
        curl https://webhook.site/ffc339e1-9323-40be-9c6e-d29b6953bc35
